version: '3.9'
services:

  laravel_app:
    build: laravel
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - TZ=Asia/Jakarta
      - NODE_OPTIONS=--max-old-space-size=8192
    command: bash -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"

  nestjs_app:
    build: nestjs
    working_dir: /var/www
    volumes:
      - ./nestjs:/var/www
    # ports:
    #   - 3001:3000
    environment:
      - TZ=Asia/Jakarta
      - NODE_OPTIONS=--max-old-space-size=8192
    command: bash -c "yarn && yarn build && yarn start:prod"

  nextjs_app:
    build: nextjs
    working_dir: /var/www
    volumes:
      - ./nextjs:/var/www
    environment:
      - TZ=Asia/Jakarta
      - NODE_OPTIONS=--max-old-space-size=8192
    # ports:
    #   - 3000:3000
    command: bash -c "yarn && yarn build && yarn start"

  webserver:
    image: caddy/caddy:2.2.1-alpine
    # restart: unless-stopped
    ports:
      - "80:80"
      # - "3000:3000"
      # - "3001:3001"
      - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - laravel_app
      - nestjs_app
      - nextjs_app

volumes:
  caddy_data:
  caddy_config:
